name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth:         0  # Required for rebase to work properly

      - name: Set up Git
        run:  |
              git config --global user.name 'github-actions'
              git config --global user.email 'github-actions@github.com'

      - name: Add upstream and rebase
        run:  |
              git remote add upstream https://github.com/google/s2-geometry-library-java.git
              git fetch upstream
              git rebase upstream/master
              git push origin HEAD:master --force-with-lease
